services:
  backend:
    build:
      context: ./backend
    container_name: locker-backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env

  mysql:
    image: mysql:8.0
    container_name: locker-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: locker_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: locker-redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: locker-rabbit
    ports:
      - "5672:5672"
      - "15672:15672"

  grafana:
    image: grafana/grafana:latest
    container_name: locker-grafana
    ports:
      - "3000:3000"

  prometheus:
    image: prom/prometheus:latest
    container_name: locker-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

volumes:
  mysql_data:
